/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cases */
        get: operations["cases_v1_cases_get"];
        put?: never;
        /** Create */
        post: operations["create_v1_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_v1_cases__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Analysis */
        post: operations["start_analysis_v1_cases__id__analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Case */
        post: operations["assign_case_v1_cases__id__assignment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_v1_cases__id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/checklist/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Checklist */
        post: operations["accept_checklist_v1_cases__id__checklist_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/consultations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consultation */
        post: operations["consultation_v1_cases__id__consultations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_v1_cases__id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_v1_cases__id__documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/documents/{doc_id}/ocr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Ocr */
        post: operations["start_ocr_v1_cases__id__documents__doc_id__ocr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/export/{kind}/{format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Case */
        get: operations["export_case_v1_cases__id__export__kind___format__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/facts/{fact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Review Fact */
        patch: operations["review_fact_v1_cases__id__facts__fact_id__patch"];
        trace?: never;
    };
    "/v1/cases/{id}/final-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Final Review */
        post: operations["final_review_v1_cases__id__final_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Review Finding */
        patch: operations["review_finding_v1_cases__id__findings__finding_id__patch"];
        trace?: never;
    };
    "/v1/cases/{id}/internal-record/{format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Internal Record */
        get: operations["internal_record_v1_cases__id__internal_record__format__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/legal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Legal */
        get: operations["get_legal_v1_cases__id__legal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/legal/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Legal Context */
        post: operations["review_legal_context_v1_cases__id__legal_context_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/legal/requirements/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Legal Requirement */
        post: operations["review_legal_requirement_v1_cases__id__legal_requirements__key__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/procedure-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Procedure Review */
        get: operations["procedure_review_v1_cases__id__procedure_review_get"];
        put?: never;
        /** Save Procedure Review */
        post: operations["save_procedure_review_v1_cases__id__procedure_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/procedure-review/{kind}/{format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Procedure Review */
        get: operations["export_procedure_review_v1_cases__id__procedure_review__kind___format__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Case Progress */
        get: operations["case_progress_v1_cases__id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Project */
        post: operations["link_project_v1_cases__id__project_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen Review */
        post: operations["reopen_review_v1_cases__id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Requirement */
        post: operations["add_requirement_v1_cases__id__requirements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/requirements/{req_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Review Requirement */
        patch: operations["review_requirement_v1_cases__id__requirements__req_id__patch"];
        trace?: never;
    };
    "/v1/cases/{id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Submission History */
        get: operations["submission_history_v1_cases__id__submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/supplements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Supplement */
        post: operations["create_supplement_v1_cases__id__supplements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Upload */
        post: operations["prepare_upload_v1_cases__id__uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/uploads/{upload_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize Upload */
        post: operations["finalize_upload_v1_cases__id__uploads__upload_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{id}/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workflow State */
        get: operations["workflow_state_v1_cases__id__workflow_get"];
        put?: never;
        /** Transition Case */
        post: operations["transition_case_v1_cases__id__workflow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Page */
        get: operations["catalog_page_v1_catalog__kind__get"];
        put?: never;
        /** Create Catalog */
        post: operations["create_catalog_v1_catalog__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/{kind}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Catalog */
        patch: operations["update_catalog_v1_catalog__kind___id__patch"];
        trace?: never;
    };
    "/v1/catalog/{kind}/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog History */
        get: operations["catalog_history_v1_catalog__kind___id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Summary */
        get: operations["dashboard_summary_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities/{kind}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity Detail */
        get: operations["entity_detail_v1_entities__kind___id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/legal-assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Legal */
        post: operations["ask_legal_v1_legal_assistant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/legal-assistant/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legal Evaluation */
        get: operations["legal_evaluation_v1_legal_assistant_evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Model Check */
        post: operations["model_check_v1_model_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Organization Options */
        get: operations["organization_options_v1_organizations_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Detail */
        get: operations["project_detail_v1_projects__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Audit */
        get: operations["project_audit_v1_projects__id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Images */
        get: operations["project_images_v1_projects__id__images_get"];
        put?: never;
        /** Add Project Image */
        post: operations["add_project_image_v1_projects__id__images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{id}/images/{image_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Image Original */
        get: operations["project_image_original_v1_projects__id__images__image_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_v1_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime */
        get: operations["runtime_v1_runtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/samples.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sample Zip */
        get: operations["sample_zip_v1_samples_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/samples/{scenario}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Sample */
        post: operations["import_sample_v1_samples__scenario__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Submissions */
        get: operations["submissions_v1_submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/test-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Test Account */
        post: operations["login_test_account_v1_test_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/test-login/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Test Accounts */
        get: operations["test_accounts_v1_test_login_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptChecklist */
        AcceptChecklist: {
            /** Candidateid */
            candidateId: string;
            /** Revision */
            revision: number;
        };
        /** AddProjectImage */
        AddProjectImage: {
            /**
             * Category
             * @enum {string}
             */
            category: "phoi_canh" | "hien_trang" | "ban_ve" | "tien_do";
            /** Contentbase64 */
            contentBase64?: string | null;
            /**
             * Description
             * @default
             */
            description?: string;
            /** Revision */
            revision: number;
            /** Title */
            title: string;
            /**
             * Url
             * @default
             */
            url?: string;
        };
        /** AddRequirement */
        AddRequirement: {
            /** Category */
            category: string;
            /** Name */
            name: string;
            /** Revision */
            revision: number;
        };
        /** Assignment */
        Assignment: {
            /**
             * Assigneeid
             * Format: uuid
             */
            assigneeId: string;
            /** Deadline */
            deadline?: string | null;
            /** Note */
            note: string;
            /** Revision */
            revision: number;
        };
        /** CatalogMutation */
        CatalogMutation: {
            /**
             * Revision
             * @default 1
             */
            revision?: number;
            /** Values */
            values: {
                [key: string]: unknown;
            };
        };
        /** Check */
        Check: {
            /** Documentids */
            documentIds?: string[];
            /** Id */
            id: string;
            /**
             * Note
             * @default
             */
            note?: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status?: "pending" | "satisfied" | "missing" | "not_applicable";
        };
        /** Consultation */
        Consultation: {
            /**
             * Response
             * @default
             */
            response?: string;
            /** Revision */
            revision: number;
            /** Text */
            text: string;
        };
        /** CreateCase */
        CreateCase: {
            /**
             * Legaldate
             * Format: date
             */
            legalDate: string;
            /** Name */
            name: string;
            /**
             * Procedure
             * @default bcnckt
             * @enum {string}
             */
            procedure?: "bcnckt" | "gpxd" | "nghiem_thu";
            /** Projectcode */
            projectCode?: string | null;
            /** Projectid */
            projectId?: string | null;
            /** Projectname */
            projectName?: string | null;
            /** Province */
            province: string;
        };
        /** CreateProject */
        CreateProject: {
            /** Code */
            code: string;
            /** Field */
            field: string;
            /**
             * Grade
             * @enum {string}
             */
            grade: "I" | "II" | "III" | "IV" | "DB";
            /**
             * Group Type
             * @enum {string}
             */
            group_type: "A" | "B" | "C" | "QG";
            /** Investment Cost */
            investment_cost: number;
            /** Investor Id */
            investor_id?: string | null;
            /** Location */
            location: string;
            /** Title */
            title: string;
        };
        /** Defect */
        Defect: {
            /** Description */
            description: string;
            /** Documentids */
            documentIds?: string[];
            /** Duedate */
            dueDate?: string | null;
            /**
             * Nonsafetyconfirmed
             * @default false
             */
            nonSafetyConfirmed?: boolean;
            /**
             * Resolution
             * @default
             */
            resolution?: string;
            /** Responsible */
            responsible: string;
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status?: "open" | "resolved";
        };
        /** FactReview */
        FactReview: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirmed" | "rejected";
            /** Note */
            note: string;
            /** Revision */
            revision: number;
            /** Value */
            value: string;
        };
        /** FinalReview */
        FinalReview: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "request_supplement" | "reviewed";
            /** Note */
            note: string;
            /** Revision */
            revision: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LegalContextReview */
        LegalContextReview: {
            /** Note */
            note: string;
            /**
             * Priorstatus
             * @enum {string}
             */
            priorStatus: "unknown" | "eligible_pending" | "ineligible" | "result_ineligible" | "result_eligible";
            /** Revision */
            revision: number;
            /**
             * Scope
             * @enum {string}
             */
            scope: "construction" | "decision_maker" | "concurrent" | "unknown";
            /**
             * Stage
             * @enum {string}
             */
            stage: "original" | "amendment" | "remaining_phase";
            /**
             * Submissiondate
             * Format: date
             */
            submissionDate: string;
        };
        /** LegalQuestion */
        LegalQuestion: {
            /** Question */
            question: string;
            /**
             * Usemodel
             * @default true
             */
            useModel?: boolean;
        };
        /** LegalRequirementReview */
        LegalRequirementReview: {
            /**
             * Applicability
             * @enum {string}
             */
            applicability: "applicable" | "not_applicable" | "unknown";
            /** Note */
            note: string;
            /** Requirementids */
            requirementIds: string[];
            /** Revision */
            revision: number;
        };
        /** Mutation */
        Mutation: {
            /** Revision */
            revision: number;
        };
        /** PrepareUpload */
        PrepareUpload: {
            /** Name */
            name: string;
            /** Requirementid */
            requirementId: string;
            /** Revision */
            revision: number;
            /**
             * Role
             * @default submission
             * @enum {string}
             */
            role?: "submission" | "reference";
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
        };
        /** ProjectLink */
        ProjectLink: {
            /** Projectcode */
            projectCode: string;
            /** Projectid */
            projectId: string;
            /** Projectname */
            projectName: string;
            /** Revision */
            revision: number;
        };
        /** ReopenReview */
        ReopenReview: {
            /** Note */
            note: string;
            /** Revision */
            revision: number;
        };
        /** RequirementReview */
        RequirementReview: {
            /** Note */
            note: string;
            /** Revision */
            revision: number;
            /**
             * Status
             * @enum {string}
             */
            status: "submitted" | "verified" | "needs_supplement";
        };
        /** RunRequest */
        RunRequest: {
            /**
             * Mode
             * @default intake
             * @enum {string}
             */
            mode?: "intake" | "comparison";
            /** Revision */
            revision: number;
            /**
             * Usemodel
             * @default false
             */
            useModel?: boolean;
        };
        /** Supplement */
        Supplement: {
            /**
             * Legaldate
             * Format: date
             */
            legalDate: string;
            /** Name */
            name: string;
            /** Reason */
            reason: string;
            /**
             * Requestid
             * Format: uuid
             */
            requestId: string;
            /** Revision */
            revision: number;
        };
        /** TestLogin */
        TestLogin: {
            /**
             * Role
             * @enum {string}
             */
            role: "officer" | "head_of_department" | "director" | "admin";
        };
        /** Upload */
        Upload: {
            /** Contentbase64 */
            contentBase64: string;
            /** Name */
            name: string;
            /** Requirementid */
            requirementId: string;
            /** Revision */
            revision: number;
            /**
             * Role
             * @default submission
             * @enum {string}
             */
            role?: "submission" | "reference";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkflowCommand */
        WorkflowCommand: {
            /**
             * Action
             * @enum {string}
             */
            action: "start" | "request_supplement" | "submit_review" | "return" | "approve" | "schedule_visit" | "require_correction" | "confirm_correction";
            /** Note */
            note: string;
            /** Revision */
            revision: number;
            /** Visitdate */
            visitDate?: string | null;
        };
        /** Review */
        app__procedure_review__Review: {
            /**
             * Authority
             * @default
             */
            authority?: string;
            /** Checks */
            checks: components["schemas"]["Check"][];
            /**
             * Conclusion
             * @default pending
             * @enum {string}
             */
            conclusion?: "pending" | "supplement" | "eligible" | "ineligible";
            /**
             * Conditions
             * @default
             */
            conditions?: string;
            /** Defects */
            defects?: components["schemas"]["Defect"][];
            /**
             * Designbasis
             * @default
             */
            designBasis?: string;
            /** Details */
            details?: {
                [key: string]: string;
            };
            /** Extensioncount */
            extensionCount?: number | null;
            /**
             * Investor
             * @default
             */
            investor?: string;
            /**
             * Location
             * @default
             */
            location?: string;
            /**
             * Observations
             * @default
             */
            observations?: string;
            /**
             * Originalform
             * @default
             * @enum {string}
             */
            originalForm?: "" | "03" | "04" | "05";
            /**
             * Parameters
             * @default
             */
            parameters?: string;
            /**
             * Participants
             * @default
             */
            participants?: string;
            /**
             * Priorpermit
             * @default
             */
            priorPermit?: string;
            /** Revision */
            revision: number;
            /**
             * Ruleversion
             * @default 2026-07.v2
             */
            ruleVersion?: string;
            /**
             * Scope
             * @default
             */
            scope?: string;
            /** Subtype */
            subtype: string;
            /** Visitdate */
            visitDate?: string | null;
        };
        /** Review */
        app__schemas__Review: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "accept" | "reject" | "defer";
            /** Note */
            note: string;
            /** Revision */
            revision: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    cases_v1_cases_get: {
        parameters: {
            query?: {
                offset?: number;
                procedure?: ("bcnckt" | "gpxd" | "nghiem_thu") | null;
                projectId?: string | null;
            };
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_v1_cases_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCase"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_v1_cases__id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_analysis_v1_cases__id__analysis_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_case_v1_cases__id__assignment_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Assignment"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_v1_cases__id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Mutation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_checklist_v1_cases__id__checklist_accept_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptChecklist"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consultation_v1_cases__id__consultations_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Consultation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_v1_cases__id__documents_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Upload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_v1_cases__id__documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_ocr_v1_cases__id__documents__doc_id__ocr_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Mutation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_case_v1_cases__id__export__kind___format__get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
                kind: "report" | "supplement" | "suspension" | "notice" | "decision";
                format: "pdf" | "docx" | "json";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_fact_v1_cases__id__facts__fact_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    final_review_v1_cases__id__final_review_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_finding_v1_cases__id__findings__finding_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__schemas__Review"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    internal_record_v1_cases__id__internal_record__format__get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
                format: "pdf" | "docx";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_legal_v1_cases__id__legal_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_legal_context_v1_cases__id__legal_context_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegalContextReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_legal_requirement_v1_cases__id__legal_requirements__key__post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegalRequirementReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    procedure_review_v1_cases__id__procedure_review_get: {
        parameters: {
            query?: {
                subtype?: string | null;
            };
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_procedure_review_v1_cases__id__procedure_review_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__procedure_review__Review"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_procedure_review_v1_cases__id__procedure_review__kind___format__get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
                kind: "review" | "minutes" | "draft" | "application";
                format: "pdf" | "docx";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    case_progress_v1_cases__id__progress_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_project_v1_cases__id__project_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectLink"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reopen_review_v1_cases__id__reopen_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReopenReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_requirement_v1_cases__id__requirements_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRequirement"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_requirement_v1_cases__id__requirements__req_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
                req_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequirementReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submission_history_v1_cases__id__submissions_get: {
        parameters: {
            query?: {
                offset?: number;
            };
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_supplement_v1_cases__id__supplements_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Supplement"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_upload_v1_cases__id__uploads_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrepareUpload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_upload_v1_cases__id__uploads__upload_id__finalize_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workflow_state_v1_cases__id__workflow_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_case_v1_cases__id__workflow_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_page_v1_catalog__kind__get: {
        parameters: {
            query?: {
                search?: string;
                category?: string;
                status?: string;
                offset?: number;
                limit?: number;
                sort?: string;
                direction?: "asc" | "desc";
            };
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                kind: "organizations" | "personnel" | "material_prices";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_catalog_v1_catalog__kind__post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                kind: "organizations" | "personnel" | "material_prices";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogMutation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_catalog_v1_catalog__kind___id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                kind: "organizations" | "personnel" | "material_prices";
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogMutation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_history_v1_catalog__kind___id__history_get: {
        parameters: {
            query?: {
                offset?: number;
            };
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                kind: "organizations" | "personnel" | "material_prices";
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_summary_v1_dashboard_get: {
        parameters: {
            query?: {
                kind?: "all" | "sample" | "real";
            };
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_detail_v1_entities__kind___id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                kind: "organization" | "personnel";
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_legal_v1_legal_assistant_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegalQuestion"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    legal_evaluation_v1_legal_assistant_evaluation_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_check_v1_model_check_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    organization_options_v1_organizations_options_get: {
        parameters: {
            query?: {
                search?: string;
            };
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projects_v1_projects_get: {
        parameters: {
            query?: {
                search?: string;
                offset?: number;
                limit?: number;
                stage?: string;
                group?: string;
                status?: string;
                sort?: string;
                direction?: "asc" | "desc";
            };
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_v1_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProject"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_detail_v1_projects__id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_audit_v1_projects__id__audit_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_images_v1_projects__id__images_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_project_image_v1_projects__id__images_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddProjectImage"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_image_original_v1_projects__id__images__image_id__content_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                id: string;
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readiness_v1_readiness_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runtime_v1_runtime_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_zip_v1_samples_zip_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_sample_v1_samples__scenario__post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path: {
                scenario: "initial" | "revised";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submissions_v1_submissions_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                procedure?: ("bcnckt" | "gpxd" | "nghiem_thu") | null;
                projectId?: string | null;
                search?: string;
                kind?: string;
                status?: string;
                dateFrom?: string;
                dateTo?: string;
                sort?: string;
                direction?: string;
                sla?: string;
            };
            header?: {
                "x-internal-token"?: string;
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_test_account_v1_test_login_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                "x-local-test-login"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_accounts_v1_test_login_accounts_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-token"?: string;
                "x-local-test-login"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
