import React,{useEffect,useState} from 'react';
import {appraisalService as api} from '../../services/appraisalService';
import {apiRequest} from '../../services/apiClient';
import type {Dossier} from '../../types/appraisal';
import {ReviewModal} from './ReviewModal';
import {SearchableSelect} from '../ui/SearchableSelect';
import {DateInput} from '../ui/DateInput';
import {DossierGrid} from './DossierGrid';
import {formatDate} from '../../lib/utils';

const button='rounded-lg border border-border dark:border-border bg-surface dark:bg-surface text-ink dark:text-ink p-2 text-sm disabled:opacity-50';
type Check={id:string;status:string;documentIds:string[];note:string};
type Defect={description:string;responsible:string;dueDate:string|null;status:string;documentIds:string[];resolution:string;nonSafetyConfirmed?:boolean};
type Review={ruleVersion:string;originalForm:string;extensionCount:number|null;subtype:string;checks:Check[];defects:Defect[];authority:string;investor:string;location:string;scope:string;parameters:string;priorPermit:string;designBasis:string;conclusion:string;conditions:string;visitDate:string|null;participants:string;observations:string;details:Record<string,string>};
type Spec={ruleVersion:string;reviewOutdated:boolean;template:{input:string;output:string;url:string};subtype:string;citation:string;types:{value:string;label:string}[];detailFields:{id:string;label:string}[];checks:{id:string;label:string;conditional:boolean;citation:string;condition:string;url:string}[];review:Review|null};
const empty:Review={ruleVersion:'',originalForm:'',extensionCount:null,subtype:'',checks:[],defects:[],authority:'',investor:'',location:'',scope:'',parameters:'',priorPermit:'',designBasis:'',conclusion:'pending',conditions:'',visitDate:null,participants:'',observations:'',details:{}};
const states=[{value:'pending',label:'Chưa đánh giá'},{value:'satisfied',label:'Đã đối chiếu, đáp ứng'},{value:'missing',label:'Thiếu / chưa đáp ứng'},{value:'not_applicable',label:'Không áp dụng'}];

export function ProcedureReview({dossier:d,onChange}:{dossier:Dossier;onChange:(d:Dossier)=>void}){
 const [spec,setSpec]=useState<Spec|null>(null),[open,setOpen]=useState(false),[draft,setDraft]=useState<Review>(empty),[initial,setInitial]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;apiRequest<Spec>(`/cases/${d.id}/procedure-review`).then(x=>{if(live)setSpec(x);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[d.id,d.revision]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const close=()=>{if(busy)return;setOpen(false);apiRequest<Spec>(`/cases/${d.id}/procedure-review`).then(setSpec).catch(e=>setError(e.message));};
 const load=()=>{if(!spec)return;const value={...empty,...Object.fromEntries(Object.keys(empty).filter(k=>spec.review&&k in spec.review).map(k=>[k,(spec.review as any)[k]])),subtype:spec.subtype,ruleVersion:spec.ruleVersion,conclusion:spec.reviewOutdated?'pending':spec.review?.conclusion||'pending',checks:(!spec.reviewOutdated&&spec.review?.checks)||spec.checks.map(c=>({id:c.id,status:'pending',documentIds:[],note:''}))};setDraft(value);setInitial(JSON.stringify(value));setOpen(true);};
 const docs=d.documents.filter(x=>x.role==='submission');
 const evidence=(ids:string[],change:(v:string[])=>void)=><fieldset className="space-y-1 max-h-40 overflow-auto rounded border border-border dark:border-border p-2"><legend className="text-xs">Tài liệu dẫn chứng</legend>{docs.length?docs.map(doc=><label key={doc.id} className="flex items-start gap-2 text-sm"><input type="checkbox" disabled={busy} checked={ids.includes(doc.id)} onChange={e=>change(e.target.checked?[...ids,doc.id]:ids.filter(id=>id!==doc.id))}/><span>{doc.name}</span></label>):<p className="text-sm">Nộp tài liệu trước khi xác nhận.</p>}</fieldset>;
 const updateCheck=(index:number,patch:Partial<Check>)=>setDraft(p=>({...p,checks:p.checks.map((c,i)=>i===index?{...c,...patch}:c)}));
 const updateDefect=(index:number,patch:Partial<Defect>)=>setDraft(p=>({...p,defects:p.defects.map((c,i)=>i===index?{...c,...patch}:c)}));
 return <section className="rounded-xl border border-border dark:border-border p-4 space-y-3 text-ink dark:text-ink">
  <h3 className="font-semibold">Phiếu rà soát chuyên môn · {d.procedure==='gpxd'?'GPXD':'Nghiệm thu'}</h3><p className="text-sm text-ink-muted dark:text-ink-muted">{spec?.citation}</p>
  {spec&&<div className="rounded-lg bg-primary-50 dark:bg-slate-800 border border-primary-200 dark:border-slate-700 p-3 text-sm text-ink dark:text-ink space-y-1"><p>Bộ đối chiếu {spec.ruleVersion} · áp dụng từ 01/07/2026</p><p>Đầu vào: {spec.template.input}</p><p>Đầu ra: {spec.template.output}</p><a className="text-primary-700 dark:text-primary-300 underline" href={spec.template.url} target="_blank" rel="noreferrer">Xem biểu mẫu trong văn bản gốc</a>{spec.reviewOutdated&&<p role="status">Phiếu đã lưu dùng checklist cũ. Mở cập nhật để rà soát phiên bản mới; lịch sử được giữ lại.</p>}</div>}
  <p className="text-sm">{spec?.review?'Đã lưu phiếu; các kết luận do cán bộ đối chiếu và xác nhận.':'Chọn thủ tục, đối chiếu tài liệu và ghi nhận các nội dung cần bổ sung.'}</p>
  <div className="flex flex-wrap gap-3"><button className={button+' !bg-primary-500 dark:!bg-primary-500 !text-white dark:!text-white'} disabled={!spec||busy||d.readOnly||!!d.finalReview} onClick={load}>{spec?.review?'Cập nhật phiếu':'Lập phiếu rà soát'}</button>
   {spec?.review&&!spec.reviewOutdated&&['pdf','docx'].map(format=><button key={format} className={button} disabled={busy} onClick={()=>run(()=>api.download(`/cases/${d.id}/procedure-review/review/${format}`,`phieu-chuyen-mon.${format}`))}>Phiếu {format.toUpperCase()}</button>)}
   {spec?.review&&!spec.reviewOutdated&&['pdf','docx'].map(format=><button key={'draft-'+format} className={button} disabled={busy} onClick={()=>run(()=>api.download(`/cases/${d.id}/procedure-review/draft/${format}`,`du-thao-${d.procedure}.${format}`))}>Dự thảo {format.toUpperCase()}</button>)}
   {spec?.review&&!spec.reviewOutdated&&d.procedure==='nghiem_thu'&&<button className={button} disabled={busy} onClick={()=>run(()=>api.download(`/cases/${d.id}/procedure-review/minutes/docx`,'bien-ban-hien-truong.docx'))}>Biên bản hiện trường DOCX</button>}
   {spec?.review&&!spec.reviewOutdated&&['pdf','docx'].map(format=><button key={'input-'+format} className={button} disabled={busy} onClick={()=>run(()=>api.download(`/cases/${d.id}/procedure-review/application/${format}`,`dau-vao-${d.procedure}.${format}`))}>{d.procedure==='gpxd'?'Đơn đề nghị':'Báo cáo hoàn thành'} {format.toUpperCase()}</button>)}
  </div>
  {!!spec?.review?.defects.length&&<DossierGrid storageKey="procedure-defects" rows={spec.review.defects.map((x,i)=>({...x,id:String(i)}))} columns={[{label:'Tồn tại',value:r=>r.description,width:340},{label:'Phụ trách',value:r=>r.responsible},{label:'Hạn khắc phục',value:r=>r.dueDate||'',render:r=>r.dueDate?formatDate(r.dueDate):'Chưa xác định'},{label:'Tình trạng',value:r=>r.status==='resolved'?'Đã khắc phục':'Chưa khắc phục'}]}/>}
  {error&&<p role="alert" className="text-red-700 dark:text-red-300">{error}</p>}
  {open&&spec&&<ReviewModal heading="Phiếu rà soát chuyên môn" dirty={busy||JSON.stringify(draft)!==initial} onClose={close}><form className="space-y-5" onSubmit={e=>{e.preventDefault();run(async()=>{onChange(await api.mutate(d.id,'/procedure-review',{revision:d.revision,...draft}));setOpen(false);});}}>
   <label className="block text-sm">Loại thủ tục<SearchableSelect value={draft.subtype} disabled={busy} options={spec.types} onChange={subtype=>run(async()=>{const next=await apiRequest<Spec>(`/cases/${d.id}/procedure-review?subtype=${subtype}`);setSpec(next);setDraft(p=>({...p,subtype,ruleVersion:next.ruleVersion,conclusion:'pending',checks:next.checks.map(c=>({id:c.id,status:'pending',note:'',documentIds:[]}))}));})}/></label>
   <p className="text-xs text-ink-muted dark:text-ink-muted">Đổi loại thủ tục sẽ đặt lại đánh giá checklist để rà soát theo yêu cầu mới.</p>
   <div className="grid gap-3 sm:grid-cols-2">{[['authority','Cơ quan có thẩm quyền'],['investor','Chủ đầu tư'],['location','Địa điểm xây dựng'],['priorPermit','Giấy phép đã cấp (nếu có)'],['scope','Phạm vi công trình / hạng mục'],['parameters','Thông số công trình'],['designBasis','Căn cứ thiết kế, quyết định']].map(([key,label])=><label key={key} className="text-sm">{label}<textarea className={button+' block w-full mt-1'} rows={2} maxLength={['authority','investor','priorPermit'].includes(key)?300:key==='location'?500:3000} disabled={busy} value={String(draft[key as keyof Review])} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}</div>
   {d.procedure==='gpxd'&&['amendment','extension'].includes(draft.subtype)&&<div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Mẫu giấy phép gốc<SearchableSelect disabled={busy} value={draft.originalForm} options={[{value:'',label:'Chưa xác định'},{value:'03',label:'Mẫu 03 — Xây dựng'},{value:'04',label:'Mẫu 04 — Sửa chữa, cải tạo, di dời'},{value:'05',label:'Mẫu 05 — Có thời hạn'}]} onChange={originalForm=>setDraft({...draft,originalForm})}/></label>{draft.subtype==='extension'&&<label className="text-sm">Lần gia hạn (mỗi lần 12 tháng)<SearchableSelect disabled={busy} value={draft.extensionCount?String(draft.extensionCount):''} options={[{value:'',label:'Chưa xác định'},{value:'1',label:'Lần 1'},{value:'2',label:'Lần 2'}]} onChange={v=>setDraft({...draft,extensionCount:v?Number(v):null})}/></label>}</div>}
   <details className="border border-border dark:border-border rounded p-3"><summary className="cursor-pointer font-medium">Thông tin chi tiết để điền dự thảo</summary><div className="grid gap-3 sm:grid-cols-2 mt-3">{spec.detailFields.map(field=><label key={field.id} className="text-sm">{field.label}<input className={button+' block w-full mt-1'} disabled={busy} maxLength={2000} value={draft.details[field.id]||''} onChange={e=>setDraft({...draft,details:{...draft.details,[field.id]:e.target.value}})}/></label>)}</div></details>
   <h4 className="font-semibold">Checklist tài liệu và điều kiện</h4>{spec.checks.map((item,i)=><fieldset key={item.id} className="rounded-xl border border-border dark:border-border p-3 space-y-3"><legend className="px-1 text-sm font-medium">{i+1}. {item.label}</legend><p className="text-xs text-ink-muted dark:text-ink-muted">{item.citation}{item.condition&&` · ${item.condition}`}</p><a className="text-xs text-primary-700 dark:text-primary-300 underline" href={item.url} target="_blank" rel="noreferrer">Đối chiếu văn bản gốc</a><SearchableSelect value={draft.checks[i]?.status||'pending'} disabled={busy} options={states.filter(s=>item.conditional||s.value!=='not_applicable')} onChange={status=>updateCheck(i,{status})}/><label className="block text-sm">Nhận xét, căn cứ và vị trí trong tài liệu<textarea maxLength={3000} className={button+' w-full block mt-1'} disabled={busy} value={draft.checks[i]?.note||''} onChange={e=>updateCheck(i,{note:e.target.value})}/></label>{evidence(draft.checks[i]?.documentIds||[],documentIds=>updateCheck(i,{documentIds}))}</fieldset>)}
   {d.procedure==='nghiem_thu'&&<><h4 className="font-semibold">Kiểm tra hiện trường và theo dõi khắc phục</h4><label className="block text-sm">Ngày kiểm tra<DateInput value={draft.visitDate||''} onChange={v=>setDraft({...draft,visitDate:v||null})}/></label>{[['participants','Thành phần tham gia'],['observations','Ghi nhận hiện trường']].map(([key,label])=><label key={key} className="block text-sm">{label}<textarea disabled={busy} className={button+' w-full block mt-1'} maxLength={key==='participants'?2000:4000} value={String(draft[key as keyof Review])} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}
    {draft.defects.map((defect,i)=><fieldset key={i} className="border border-border dark:border-border rounded p-3 space-y-3"><legend>Tồn tại {i+1}</legend>{[['description','Nội dung'],['responsible','Đơn vị / người phụ trách'],['resolution','Giải trình khắc phục']].map(([key,label])=><label key={key} className="block text-sm">{label}<textarea disabled={busy} required={key!=='resolution'} maxLength={key==='responsible'?200:key==='description'?1500:2000} className={button+' block w-full'} value={String(defect[key as keyof Defect])} onChange={e=>updateDefect(i,{[key]:e.target.value})}/></label>)}<label className="block text-sm">Hạn khắc phục<DateInput value={defect.dueDate||''} onChange={v=>updateDefect(i,{dueDate:v||null})}/></label><SearchableSelect disabled={busy} value={defect.status} options={[{value:'open',label:'Chưa khắc phục'},{value:'resolved',label:'Đã đối chiếu tài liệu khắc phục'}]} onChange={status=>updateDefect(i,{status})}/>{draft.subtype==='conditional'&&defect.status==='open'&&<label className="flex gap-2 items-start text-sm"><input type="checkbox" disabled={busy} checked={!!defect.nonSafetyConfirmed} onChange={e=>updateDefect(i,{nonSafetyConfirmed:e.target.checked})}/>Đã đối chiếu bằng chứng: tồn tại không ảnh hưởng chịu lực, thời hạn sử dụng và công năng. Phải có giải trình, hạn khắc phục và điều kiện sử dụng.</label>}{evidence(defect.documentIds,documentIds=>updateDefect(i,{documentIds}))}<button type="button" disabled={busy} className={button} onClick={()=>setDraft({...draft,defects:draft.defects.filter((_,j)=>i!==j)})}>Bỏ dòng tồn tại</button></fieldset>)}<button type="button" disabled={busy} className={button} onClick={()=>setDraft({...draft,defects:[...draft.defects,{description:'',responsible:'',dueDate:null,status:'open',documentIds:[],resolution:''}]})}>Thêm tồn tại cần khắc phục</button></>}
   <label className="block text-sm">Đề xuất<SearchableSelect disabled={busy} value={draft.conclusion} options={[{value:'pending',label:'Chưa kết luận'},{value:'supplement',label:'Đề nghị bổ sung'},{value:'eligible',label:'Đề xuất đủ điều kiện'},{value:'ineligible',label:'Đề xuất chưa đủ điều kiện'}]} onChange={conclusion=>setDraft({...draft,conclusion})}/></label><label className="block text-sm">Yêu cầu / điều kiện / nội dung cần xử lý<textarea className={button+' w-full block'} disabled={busy} rows={3} maxLength={4000} value={draft.conditions} onChange={e=>setDraft({...draft,conditions:e.target.value})}/></label>
   {error&&<p role="alert" className="text-red-700 dark:text-red-300">{error}</p>}<button className={button+' !bg-primary-500 dark:!bg-primary-500 !text-white dark:!text-white'} disabled={busy}>{busy?'Đang lưu…':'Lưu phiếu rà soát'}</button>
  </form></ReviewModal>}
 </section>;
}
